import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink, Outlet } from 'react-router-dom';
import { useRole } from '../../context/RoleContext';
import { useAuth } from '../../context/AuthContext';
import { useClients } from '../../hooks/useClients';
import { canSwitchClient } from '@dc-hub/asset-library';
import { isConfigured } from '../../lib/supabase';
export default function AppLayout() {
    const { role, setRole, activeClient, setActiveClient, user } = useRole();
    const { signOut } = useAuth();
    const { clients } = useClients();
    const configured = isConfigured();
    if (role === 'public') {
        return (_jsx("div", { className: "min-h-full bg-bg", children: _jsx(Outlet, {}) }));
    }
    return (_jsxs("div", { className: "flex flex-col min-h-full bg-bg", children: [_jsxs("header", { className: "flex items-center h-11 px-5 border-b border-border bg-surface shrink-0", children: [_jsxs("div", { className: "flex items-center gap-2 mr-6", children: [_jsx("div", { className: "w-6 h-6 rounded-[28%_38%] bg-cosmos-black flex items-center justify-center", children: _jsx("span", { className: "text-clear-white text-[10px] font-bold font-sans leading-none", children: "C" }) }), _jsx("span", { className: "font-sans text-xs font-bold tracking-[0.14em] uppercase text-cosmos-black", children: "DC HUB" })] }), _jsxs("nav", { className: "flex items-center gap-1 flex-1", children: [['gallery', 'activity'].map(path => (_jsx(NavLink, { to: path === 'gallery' ? '/' : `/${path}`, end: path === 'gallery', className: ({ isActive }) => `px-3 py-1 text-sm font-sans rounded-sm transition-colors duration-fast ${isActive ? 'text-cosmos-black font-medium' : 'text-text-muted hover:text-cosmos-black'}`, children: path.charAt(0).toUpperCase() + path.slice(1) }, path))), canSwitchClient(role) && (_jsx(NavLink, { to: "/clients", className: ({ isActive }) => `px-3 py-1 text-sm font-sans rounded-sm transition-colors duration-fast ${isActive ? 'text-cosmos-black font-medium' : 'text-text-muted hover:text-cosmos-black'}`, children: "Clients" })), _jsx(NavLink, { to: "/settings", className: ({ isActive }) => `px-3 py-1 text-sm font-sans rounded-sm transition-colors duration-fast ${isActive ? 'text-cosmos-black font-medium' : 'text-text-muted hover:text-cosmos-black'}`, children: "Settings" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [canSwitchClient(role) && activeClient && (_jsxs("div", { className: "relative flex items-center gap-2 border border-border rounded-sm px-2 py-1", children: [_jsx("span", { className: "text-[10px] font-sans font-bold uppercase tracking-label text-text-muted", children: "Client" }), _jsx("span", { className: "text-sm font-sans text-cosmos-black", children: activeClient.name }), _jsx("div", { className: "w-6 h-6 rounded-[28%_38%] flex items-center justify-center text-[9px] font-bold font-sans text-clear-white", style: { backgroundColor: activeClient.accent }, children: activeClient.initials }), _jsx("select", { className: "absolute inset-0 opacity-0 cursor-pointer w-full", value: activeClient.id, onChange: e => {
                                            const c = clients.find(c => c.id === e.target.value);
                                            if (c)
                                                setActiveClient(c);
                                        }, "aria-label": "Switch client", children: clients.map(c => (_jsx("option", { value: c.id, children: c.name }, c.id))) })] })), _jsx("button", { className: "w-7 h-7 flex items-center justify-center text-text-muted hover:text-cosmos-black transition-colors", children: _jsxs("svg", { width: "16", height: "16", viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: "1.5", children: [_jsx("path", { d: "M8 2a4 4 0 0 1 4 4v2.5l1 1.5H3l1-1.5V6a4 4 0 0 1 4-4Z" }), _jsx("path", { d: "M6.5 13a1.5 1.5 0 0 0 3 0" })] }) }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-7 h-7 rounded-[28%_38%] bg-cosmos-black flex items-center justify-center", children: _jsx("span", { className: "text-clear-white text-[10px] font-bold font-sans", children: user.initials }) }), _jsxs("div", { className: "hidden sm:flex flex-col items-end leading-none", children: [_jsx("span", { className: "text-sm font-sans font-medium text-cosmos-black", children: user.name }), _jsx("span", { className: "text-[10px] font-sans font-bold uppercase tracking-label text-text-muted", children: role })] })] }), configured ? (_jsx("button", { onClick: signOut, className: "text-[11px] font-sans text-text-muted hover:text-cosmos-black transition-colors border border-border rounded-sm px-2 py-1", children: "Sign out" })) : (_jsxs("select", { value: role, onChange: e => setRole(e.target.value), className: "ml-2 text-[10px] font-sans border border-border rounded-sm px-1 py-0.5 text-text-muted bg-surface", title: "Dev: switch role", children: [_jsx("option", { value: "public", children: "Public" }), _jsx("option", { value: "client", children: "Client" }), _jsx("option", { value: "editor", children: "Editor" }), _jsx("option", { value: "admin", children: "Admin" })] }))] })] }), _jsx("main", { className: "flex-1 overflow-hidden", children: _jsx(Outlet, {}) })] }));
}
