import type { Asset, Client, Comment } from './types.js'

export const MOCK_CLIENTS: Client[] = [
  { id: 'meridian', name: 'Meridian Labs', accent: '#2E6E4E', initials: 'ML' },
  { id: 'northwind', name: 'Northwind', accent: '#2B5BD7', initials: 'NW' },
  { id: 'volta', name: 'Volta Studio', accent: '#B8472D', initials: 'VS' },
]

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'a1',
    clientId: 'meridian',
    name: 'Sealing — pitch deck',
    entityType: 'product',
    entity: 'Sealing',
    formats: ['Presentation'],
    angle: 'brand',
    status: 'approved',
    perm: 'client',
    version: 'v3-8-0',
    latest: true,
    avg: 4.7,
    count: 11,
    comments: 6,
    approval: 'approved',
    updatedAt: '2026-06-28T10:00:00Z',
  },
  {
    id: 'a2',
    clientId: 'meridian',
    name: 'Sealing — pitch deck',
    entityType: 'product',
    entity: 'Sealing',
    formats: ['Presentation'],
    angle: 'brand',
    status: 'archived',
    perm: 'client',
    version: 'v2-1-0',
    latest: false,
    avg: 4.2,
    count: 9,
    comments: 4,
    approval: 'approved',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'a3',
    clientId: 'meridian',
    name: 'Cloud — pitch deck',
    entityType: 'product',
    entity: 'Cloud',
    formats: ['Presentation'],
    angle: 'brand',
    status: 'review',
    perm: 'client',
    version: 'v1-2-0',
    latest: true,
    avg: 4.0,
    count: 3,
    comments: 2,
    approval: 'pending',
    updatedAt: '2026-06-30T10:00:00Z',
  },
  {
    id: 'a4',
    clientId: 'meridian',
    name: 'Spring campaign — hero',
    entityType: 'customer',
    entity: 'Waxing',
    formats: ['Social', 'Banner'],
    angle: 'campaign',
    status: 'review',
    perm: 'client',
    version: 'v1-1-0',
    latest: true,
    avg: 4.5,
    count: 8,
    comments: 6,
    approval: 'pending',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'a5',
    clientId: 'meridian',
    name: 'Brand film — cut 03',
    entityType: 'product',
    entity: 'Sealing',
    formats: ['Video'],
    angle: 'brand',
    status: 'approved',
    perm: 'client',
    version: 'v3-8-0',
    latest: true,
    avg: 4.8,
    count: 12,
    comments: 9,
    approval: 'approved',
    updatedAt: '2026-06-25T10:00:00Z',
  },
  {
    id: 'a6',
    clientId: 'meridian',
    name: 'Retail print set',
    entityType: 'partner',
    entity: 'ProExpo',
    formats: ['Print'],
    angle: 'retail',
    status: 'published',
    perm: 'public',
    version: 'v2-8-0',
    latest: true,
    avg: 4.6,
    count: 21,
    comments: 14,
    approval: 'approved',
    updatedAt: '2026-06-20T10:00:00Z',
  },
  {
    id: 'a7',
    clientId: 'northwind',
    name: 'Q3 Campaign brief',
    entityType: 'customer',
    entity: 'Northwind',
    formats: ['Document'],
    angle: 'strategy',
    status: 'draft',
    perm: 'internal',
    version: 'v1-0-0',
    latest: true,
    avg: 0,
    count: 0,
    comments: 0,
    approval: 'none',
    updatedAt: '2026-07-02T08:00:00Z',
  },
]

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    assetId: 'a1',
    author: 'Petr Mucha',
    role: 'editor',
    body: 'Final version ready for client sign-off.',
    createdAt: '2026-06-28T10:05:00Z',
  },
  {
    id: 'c2',
    assetId: 'a1',
    author: 'Jana K.',
    role: 'member',
    body: 'Looks great, approved!',
    createdAt: '2026-06-29T09:20:00Z',
  },
]
